
language: ruby

rvm:
  #- 1.8.7 # over from rufus-scheduler 3.4.0
  #- 1.9.2
  - 1.9.3
  #- 2.0.0
  #- 2.1.1
  #- 2.2.3
  - 2.3.3
  - 2.4.6
  - 2.5.5
  #- 2.6.6 # keeps failing on Travis for discard_past: true, but not locally
  - 2.7.1
  #- jruby-9.1.13.0
  - jruby-9.2.5.0

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0
#    #- env: JRUBY_OPTS="--profile.api"

#before_install: gem install bundler
script: bundle exec rspec

branches:
  only:
    - master
  #except:
  #  - master

cache: bundler

#env:
#  - WHATEVER_DEFAULT_TIMEOUT=7

